# Generated by Django 5.1 on 2024-09-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('email_addr', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
